# Generated by Django 3.1.7 on 2021-10-12 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_cliente', models.CharField(max_length=500)),
                ('contacto_empresa', models.CharField(max_length=50)),
                ('nombre_oportunidad', models.CharField(max_length=50)),
                ('monto_oportunidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Ganada', 'Ganada'), ('No ganada', 'No ganada'), ('Cancelada(Descartada)', 'Cancelada(Descartada)')], max_length=50)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.persona')),
            ],
        ),
    ]
