# Generated by Django 3.1.7 on 2021-10-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oportunidad', models.IntegerField()),
                ('contactos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creador', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('sitio_web', models.URLField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('usuarios_empresa', models.IntegerField()),
            ],
        ),
    ]
